import type { Dispatch, SetStateAction } from 'react'
import type { SearchHit } from '@/lib/ipc'
import type { WorkspaceTab } from '@/lib/workspace'
import type { AppViewModel, ConfirmationRequest } from '@/app/types'
import type { useFileOperations } from '@/app/useFileOperations'
import type { useJobs } from '@/app/useJobs'
import type { useLibraries } from '@/app/useLibraries'
import type { useMediaMerge } from '@/app/useMediaMerge'
import type { usePlans } from '@/app/usePlans'
import type { useSearchWorkspace } from '@/app/useSearchWorkspace'
import type { useSpotlight } from '@/app/useSpotlight'

type Libraries = ReturnType<typeof useLibraries>
type Search = ReturnType<typeof useSearchWorkspace>
type Plans = ReturnType<typeof usePlans>
type Jobs = ReturnType<typeof useJobs>
type Merge = ReturnType<typeof useMediaMerge>
type Spotlight = ReturnType<typeof useSpotlight>
type FileOperations = ReturnType<typeof useFileOperations>

export function assembleAppViewModel(input: {
  tab: WorkspaceTab
  setTab: Dispatch<SetStateAction<WorkspaceTab>>
  error: string | null
  setError: Dispatch<SetStateAction<string | null>>
  notice: string | null
  setNotice: Dispatch<SetStateAction<string | null>>
  confirmation: ConfirmationRequest | null
  setConfirmation: Dispatch<SetStateAction<ConfirmationRequest | null>>
  closePromptOpen: boolean
  setClosePromptOpen: Dispatch<SetStateAction<boolean>>
  busy: string | null
  scanCompleted: boolean
  scanPercentDisplay: number | null
  scanPhaseLabel: string
  libraries: Libraries
  search: Search
  spotlight: Spotlight
  jobs: Jobs
  merge: Merge
  plans: Plans
  fileOperations: FileOperations
  runConfirmation: () => Promise<void>
  handleScan: () => Promise<void>
  handleScanControl: (action: 'pause' | 'resume' | 'cancel') => Promise<void>
  handleRemoveLibrary: (libraryId: string, name: string) => void
  handleSendSelectionTo: (target: Exclude<WorkspaceTab, 'search' | 'jobs'>) => void
  handleOpen: (hit: SearchHit) => Promise<void>
  handleCopyPath: (hit: SearchHit) => Promise<void>
  handleMinimizeToTray: () => Promise<void>
  handleQuitApp: () => Promise<void>
  openSpotlightHit: (hit: SearchHit) => Promise<void>
}): AppViewModel {
  const {
    libraries,
    search,
    spotlight,
    jobs,
    merge,
    plans,
    fileOperations,
  } = input

  return {
    ipcReady: libraries.ipcReady,
    libraries: libraries.libraries,
    selectedLibraryId: libraries.selectedLibraryId,
    setSelectedLibraryId: libraries.setSelectedLibraryId,
    editingLibraryId: libraries.editingLibraryId,
    setEditingLibraryId: libraries.setEditingLibraryId,
    libraryDraft: libraries.libraryDraft,
    setLibraryDraft: libraries.setLibraryDraft,
    ruleSets: plans.ruleSets,
    selectedRuleSetId: plans.selectedRuleSetId,
    setSelectedRuleSetId: plans.setSelectedRuleSetId,
    organizeDirectory: plans.organizeDirectory,
    setOrganizeDirectory: plans.setOrganizeDirectory,
    organizeDirectoryId: plans.organizeDirectoryId,
    organizeStep: plans.organizeStep,
    setOrganizeStep: plans.setOrganizeStep,
    organizeFilter: plans.organizeFilter,
    setOrganizeFilter: plans.setOrganizeFilter,
    organizeFilterPreview: plans.organizeFilterPreview,
    organizeFilterPreviewTotal: plans.organizeFilterPreviewTotal,
    organizeFilterPreviewOffset: plans.organizeFilterPreviewOffset,
    organizeFilterPreviewHasMore: plans.organizeFilterPreviewHasMore,
    organizeFilterPreviewBusy: plans.organizeFilterPreviewBusy,
    organizeDirectoryPreview: plans.organizeDirectoryPreview,
    organizeDirectoryPreviewTotal: plans.organizeDirectoryPreviewTotal,
    organizeDirectoryPreviewOffset: plans.organizeDirectoryPreviewOffset,
    organizeDirectoryPreviewHasMore: plans.organizeDirectoryPreviewHasMore,
    organizeDirectoryPreviewBusy: plans.organizeDirectoryPreviewBusy,
    organizeDirectoryPreviewSort: plans.organizeDirectoryPreviewSort,
    organizeDirectoryPreviewSortDirection: plans.organizeDirectoryPreviewSortDirection,
    organizeRuleDraft: plans.organizeRuleDraft,
    setOrganizeRuleDraft: plans.setOrganizeRuleDraft,
    organizePreview: plans.organizePreview,
    organizeSnapshot: plans.organizeSnapshot,
    organizeCanPick: plans.organizeCanPick,
    organizeCanRules: plans.organizeCanRules,
    organizeBlockReason: plans.organizeBlockReason,
    libraryForOrganize: plans.libraryForOrganize,
    organizeBusy: plans.planBusy === 'organize',
    organizePreviewBusy: plans.organizePreviewBusy,
    handlePickOrganizeDirectory: plans.handlePickOrganizeDirectory,
    handleUseOrganizeDirectory: plans.handleUseOrganizeDirectory,
    handleOrganizeDirectoryChange: plans.handleOrganizeDirectoryChange,
    handleOrganizeFilterChange: plans.handleOrganizeFilterChange,
    handleOrganizePreviewSort: plans.handleOrganizePreviewSort,
    handleOrganizeDirectoryPreviewPage: plans.handleOrganizeDirectoryPreviewPage,
    handleOrganizeFilterPreviewPage: plans.handleOrganizeFilterPreviewPage,
    handleOrganizeEnterDirectory: plans.handleOrganizeEnterDirectory,
    handleOrganizeGoParent: plans.handleOrganizeGoParent,
    canOrganizeGoParent: plans.canOrganizeGoParent,
    handleOrganizeNextFromFilter: plans.handleOrganizeNextFromFilter,
    handleOrganizeNextFromRules: plans.handleOrganizeNextFromRules,
    handleOrganizePreview: plans.handleOrganizePreview,
    tab: input.tab,
    setTab: input.setTab,
    merge,
    query: search.query,
    setQuery: search.setQuery,
    hits: search.hits,
    hitTotal: search.hitTotal,
    searchElapsed: search.searchElapsed,
    searchBusy: search.searchBusy,
    searchKind: search.searchKind,
    setSearchKind: search.setSearchKind,
    searchSort: search.searchSort,
    searchSortDirection: search.searchSortDirection,
    setSearchSortDirection: search.setSearchSortDirection,
    searchScope: search.searchScope,
    setSearchScope: search.setSearchScope,
    searchDirectory: search.searchDirectory,
    setSearchDirectory: search.setSearchDirectory,
    searchOffset: search.searchOffset,
    searchHasMore: search.searchHasMore,
    selectedHit: search.selectedHit,
    setSelectedHit: search.setSelectedHit,
    fileViewMode: search.fileViewMode,
    setFileViewMode: search.setFileViewMode,
    treePath: search.treePath,
    setTreePath: search.setTreePath,
    enterTreeDirectory: search.enterTreeDirectory,
    treeHits: search.treeHits,
    treeTotal: search.treeTotal,
    treeOffset: search.treeOffset,
    treeHasMore: search.treeHasMore,
    treeBusy: search.treeBusy,
    treeSort: search.treeSort,
    treeSortDirection: search.treeSortDirection,
    selectedEntryIds: search.selectedEntryIds,
    setSelectedEntryIds: search.setSelectedEntryIds,
    preview: search.preview,
    inspectorOpen: search.inspectorOpen,
    setInspectorOpen: search.setInspectorOpen,
    scan: libraries.scan,
    scanJobId: libraries.scanJobId,
    busy: input.busy,
    error: input.error,
    setError: input.setError,
    notice: input.notice,
    setNotice: input.setNotice,
    confirmation: input.confirmation,
    setConfirmation: input.setConfirmation,
    fileOperation: fileOperations.fileOperation,
    fileOperationBusy: fileOperations.fileOperationBusy,
    fileOperationProgress: fileOperations.fileOperationProgress,
    setFileOperation: fileOperations.setFileOperation,
    handleFileRename: fileOperations.handleFileRename,
    handleFileMove: fileOperations.handleFileMove,
    handleFileDelete: fileOperations.handleFileDelete,
    submitFileOperation: fileOperations.submitFileOperation,
    pickFileOperationDirectory: fileOperations.pickFileOperationDirectory,
    ruleActionBusy: plans.ruleActionBusy,
    ruleDraft: plans.ruleDraft,
    setRuleDraft: plans.setRuleDraft,
    collision: plans.collision,
    setCollision: plans.setCollision,
    template: plans.template,
    renameGroups: plans.renameGroups,
    setRenameGroups: plans.setRenameGroups,
    renameRuleSelected: plans.renameRuleSelected,
    handleToggleRenameRule: plans.handleToggleRenameRule,
    handleToggleAllRenameRules: plans.handleToggleAllRenameRules,
    selectedOps: plans.selectedOps,
    setSelectedOps: plans.setSelectedOps,
    duplicateGroups: plans.duplicateGroups,
    keepStrategy: plans.keepStrategy,
    setKeepStrategy: plans.setKeepStrategy,
    duplicateScope: plans.duplicateScope,
    setDuplicateScope: plans.setDuplicateScope,
    duplicateDirectory: plans.duplicateDirectory,
    setDuplicateDirectory: plans.setDuplicateDirectory,
    duplicateHashStrategy: plans.duplicateHashStrategy,
    setDuplicateHashStrategy: plans.setDuplicateHashStrategy,
    handlePickDuplicateDirectory: plans.handlePickDuplicateDirectory,
    duplicateStep: plans.duplicateStep,
    setDuplicateStep: plans.setDuplicateStep,
    duplicateFilter: plans.duplicateFilter,
    setDuplicateFilter: plans.setDuplicateFilter,
    handleDuplicateFilterChange: plans.handleDuplicateFilterChange,
    duplicateFilterPreview: plans.duplicateFilterPreview,
    duplicateFilterPreviewTotal: plans.duplicateFilterPreviewTotal,
    duplicateFilterPreviewOffset: plans.duplicateFilterPreviewOffset,
    duplicateFilterPreviewHasMore: plans.duplicateFilterPreviewHasMore,
    duplicateFilterPreviewBusy: plans.duplicateFilterPreviewBusy,
    duplicateAnalysisProgress: plans.duplicateAnalysisProgress,
    activeGroupId: plans.activeGroupId,
    setActiveGroupId: plans.setActiveGroupId,
    groupsPaneWidth: plans.groupsPaneWidth,
    setGroupsPaneWidth: plans.setGroupsPaneWidth,
    handleDuplicateToggleKeep: plans.handleDuplicateToggleKeep,
    handleDuplicateResetGroup: plans.handleDuplicateResetGroup,
    duplicatePreview: plans.duplicatePreview,
    duplicatePreviewTotal: plans.duplicatePreviewTotal,
    duplicatePreviewOffset: plans.duplicatePreviewOffset,
    duplicatePreviewHasMore: plans.duplicatePreviewHasMore,
    duplicatePreviewBusy: plans.duplicatePreviewBusy,
    duplicatePreviewSort: plans.duplicatePreviewSort,
    duplicatePreviewSortDirection: plans.duplicatePreviewSortDirection,
    handleDuplicatePreviewSort: plans.handleDuplicatePreviewSort,
    handleDuplicatePreviewPage: plans.handleDuplicatePreviewPage,
    handleDuplicateFilterPreviewPage: plans.handleDuplicateFilterPreviewPage,
    handleDuplicateEnterDirectory: plans.handleDuplicateEnterDirectory,
    handleDuplicateGoParent: plans.handleDuplicateGoParent,
    handleDuplicateDirectoryChange: plans.handleDuplicateDirectoryChange,
    handleDuplicateKeepStrategyChange: plans.handleDuplicateKeepStrategyChange,
    canDuplicateGoParent: plans.canDuplicateGoParent,
    handleUseDuplicateDirectory: plans.handleUseDuplicateDirectory,
    renameDirectory: plans.renameDirectory,
    setRenameDirectory: plans.setRenameDirectory,
    renameStep: plans.renameStep,
    setRenameStep: plans.setRenameStep,
    renameFilter: plans.renameFilter,
    handleRenameFilterChange: plans.handleRenameFilterChange,
    renameFilterPreview: plans.renameFilterPreview,
    renameFilterPreviewTotal: plans.renameFilterPreviewTotal,
    renameFilterPreviewOffset: plans.renameFilterPreviewOffset,
    renameFilterPreviewHasMore: plans.renameFilterPreviewHasMore,
    renameFilterPreviewBusy: plans.renameFilterPreviewBusy,
    renamePreview: plans.renamePreview,
    renamePreviewTotal: plans.renamePreviewTotal,
    renamePreviewOffset: plans.renamePreviewOffset,
    renamePreviewHasMore: plans.renamePreviewHasMore,
    renamePreviewLoading: plans.renamePreviewLoading,
    renamePreviewSort: plans.renamePreviewSort,
    renamePreviewSortDirection: plans.renamePreviewSortDirection,
    handleRenamePreviewSort: plans.handleRenamePreviewSort,
    handleRenamePreviewPage: plans.handleRenamePreviewPage,
    handleRenameFilterPreviewPage: plans.handleRenameFilterPreviewPage,
    handleRenameEnterDirectory: plans.handleRenameEnterDirectory,
    handleRenameGoParent: plans.handleRenameGoParent,
    handlePickRenameDirectory: plans.handlePickRenameDirectory,
    handleUseRenameDirectory: plans.handleUseRenameDirectory,
    handleRenameDirectoryChange: plans.handleRenameDirectoryChange,
    handleRenameNextFromFilter: plans.handleRenameNextFromFilter,
    handleRenameNextFromRules: plans.handleRenameNextFromRules,
    renameBlockReason: plans.renameBlockReason,
    libraryForRename: plans.libraryForRename,
    canRenameScope: plans.canRenameScope,
    canRenameGoParent: plans.canRenameGoParent,
    renamePreviewBusy: plans.renamePreviewBusy,
    analyzeBlockReason: plans.analyzeBlockReason,
    libraryForDirectory: plans.libraryForDirectory,
    lastExecuteJobId: plans.lastExecuteJobId,
    executeProgress: plans.executeProgress,
    jobs: jobs.jobs,
    jobsLoading: jobs.jobsLoading,
    selectedJobId: jobs.selectedJobId,
    closePromptOpen: input.closePromptOpen,
    setClosePromptOpen: input.setClosePromptOpen,
    librarySourceOpen: libraries.librarySourceOpen,
    setLibrarySourceOpen: libraries.setLibrarySourceOpen,
    spotlightOpen: spotlight.spotlightOpen,
    setSpotlightOpen: spotlight.setSpotlightOpen,
    spotlightQuery: spotlight.spotlightQuery,
    setSpotlightQuery: spotlight.setSpotlightQuery,
    spotlightHits: spotlight.spotlightHits,
    spotlightBusy: spotlight.spotlightBusy,
    spotlightActiveIndex: spotlight.spotlightActiveIndex,
    setSpotlightActiveIndex: spotlight.setSpotlightActiveIndex,
    allLibrariesSelected: libraries.allLibrariesSelected,
    hasLibraries: libraries.hasLibraries,
    selectedLibrary: libraries.selectedLibrary,
    selectedRuleSet: plans.selectedRuleSet,
    scanning: libraries.scanning,
    scanPaused: libraries.scanPaused,
    removingLibrary: libraries.removingLibrary,
    removalProgress: libraries.removalProgress,
    refreshingLibraries: libraries.refreshing,
    libraryRootHits: libraries.libraryRootHits,
    treeRootPath: libraries.treeRootPathFor(search.treePath),
    pendingTreePath: search.pendingTreePath,
    loadJobs: jobs.loadJobs,
    openJobDetails: jobs.openJobDetails,
    resumeMediaMerge: jobs.resumeMediaMerge,
    handleRefreshLibraries: libraries.handleRefreshLibraries,
    runSearch: search.runSearch,
    handleAddLibrary: libraries.handleAddLibrary,
    handleAddCustomLibrary: libraries.handleAddCustomLibrary,
    handleAddEntireComputer: libraries.handleAddEntireComputer,
    handleScan: input.handleScan,
    handleScanControl: input.handleScanControl,
    runConfirmation: input.runConfirmation,
    handleRemoveLibrary: input.handleRemoveLibrary,
    handleOpen: input.handleOpen,
    handleMinimizeToTray: input.handleMinimizeToTray,
    handleQuitApp: input.handleQuitApp,
    openSpotlightHit: input.openSpotlightHit,
    handleCopyPath: input.handleCopyPath,
    handleSendSelectionTo: input.handleSendSelectionTo,
    handleUpdateLibrary: libraries.handleUpdateLibrary,
    handleCreateRuleSet: plans.handleCreateRuleSet,
    handleUpdateRuleSet: plans.handleUpdateRuleSet,
    handleRefreshRuleSet: plans.handleRefreshRuleSet,
    handleToggleRuleSet: plans.handleToggleRuleSet,
    handleRuleSetPriority: plans.handleRuleSetPriority,
    handleCloneRuleSet: plans.handleCloneRuleSet,
    handleDeleteRuleSet: plans.handleDeleteRuleSet,
    handleExportRuleSet: plans.handleExportRuleSet,
    handleImportRuleSet: plans.handleImportRuleSet,
    activePlan: plans.activePlan,
    handleRulesPreview: plans.handleRulesPreview,
    handleRenamePreview: plans.handleRenamePreview,
    handleAnalyzeDuplicates: plans.handleAnalyzeDuplicates,
    handleExecutePlan: plans.handleExecutePlan,
    handleRollback: plans.handleRollback,
    handleJobRollback: plans.handleJobRollback,
    selectedCount: plans.selectedCount,
    canPreviewScope: plans.canPreviewScope,
    scanPercentDisplay: input.scanPercentDisplay,
    scanCompleted: input.scanCompleted,
    scanPhaseLabel: input.scanPhaseLabel,
    changeSearchSort: search.changeSearchSort,
    changeTreeSort: search.changeTreeSort,
    changeTreePage: search.changeTreePage,
    revealInTree: (hit) => search.revealInTree(hit, libraries.setSelectedLibraryId),
  }
}
