import { CHAIN_FUNCS } from "../rules/placeholders.ts";
import type { AssistantItem, AssistantParam } from "./types.ts";

const RENAME: AssistantItem["contexts"] = ["rename-template"];
const RULE: AssistantItem["contexts"] = ["search", "scope-filter", "rename-group-filter"];

function field(id: string, label: string, value: string, group: string): AssistantItem {
  return {
    id,
    label,
    value,
    group,
    kind: "field",
    engine: "rename-field",
    contexts: RENAME,
  };
}

function snippet(id: string, label: string, value: string, group: string): AssistantItem {
  return {
    id,
    label,
    value,
    group,
    kind: "snippet",
    engine: "rename-snippet",
    contexts: RENAME,
  };
}

function chain(
  id: string,
  label: string,
  value: string,
  group: string,
  params?: AssistantParam[],
): AssistantItem {
  return {
    id,
    label,
    value,
    group,
    kind: params?.length ? "parameterized-chain" : "chain",
    engine: "rename-chain",
    contexts: RENAME,
    params,
  };
}

export const RENAME_ITEMS: AssistantItem[] = [
  field("rename-name", "文件名（不含扩展名）", "{name}", "文件字段"),
  field("rename-stem", "文件主干名", "{stem}", "文件字段"),
  field("rename-filename", "完整文件名", "{filename}", "文件字段"),
  field("rename-ext", "扩展名", "{ext}", "文件字段"),
  field("rename-ext-no-dot", "扩展名（不含点）", "{ext_no_dot}", "文件字段"),
  field("rename-parent", "所在目录", "{parent}", "目录字段"),
  field("rename-grandparent", "上级目录", "{grandparent}", "目录字段"),
  field("rename-ancestor-1", "上一级目录", "{ancestor(-1)}", "目录字段"),
  field("rename-drive", "盘符或根名", "{drive}", "目录字段"),
  field("rename-root", "资料库根目录名", "{root}", "目录字段"),
  field("rename-path", "完整路径", "{path}", "目录字段"),
  field("rename-relpath", "相对路径", "{relPath}", "目录字段"),
  field("rename-size", "文件大小（字节）", "{size}", "文件属性"),
  snippet("rename-size-friendly", "友好文件大小", "{size.format_size()}", "文件属性"),
  field("rename-kind", "文件类型", "{kind}", "文件属性"),
  field("rename-is-dir", "是否为目录", "{is_dir}", "文件属性"),
  field("rename-depth", "目录层级", "{depth}", "文件属性"),
  field("rename-children-count", "子项数量", "{children.count}", "目录统计"),
  field("rename-children-file-count", "文件数量", "{children.file_count}", "目录统计"),
  field("rename-children-dir-count", "目录数量", "{children.dir_count}", "目录统计"),
  field("rename-children-video-count", "视频数量", "{children.video_count}", "目录统计"),
  field("rename-children-image-count", "图片数量", "{children.image_count}", "目录统计"),
  field("rename-children-useful-count", "有效文件数量", "{children.useful_file_count}", "目录统计"),
  field("rename-children-main-name", "主文件名称", "{children.main_name}", "目录统计"),
  field("rename-children-main-stem", "主文件主干名", "{children.main_stem}", "目录统计"),
  field("rename-children-main-kind", "主文件类型", "{children.main_kind}", "目录统计"),
  field("rename-children-has-unique-video", "是否存在唯一视频", "{children.has_unique_video}", "目录统计"),
  field("rename-children-main-video-stem", "唯一视频主干名", "{children.main_video.stem}", "目录统计"),
  field("rename-children-main-video-name", "唯一视频文件名", "{children.main_video.name}", "目录统计"),
  field("rename-children-main-video-ext", "唯一视频扩展名", "{children.main_video.ext}", "目录统计"),
  field("rename-peer-dir", "同名目录是否存在", "{peer_dir.exists}", "目录统计"),
  field("rename-seq", "当前序号", "{seq}", "动态值"),
  snippet("rename-seq-pad3", "三位序号", "{seq.pad(3, '0')}", "动态值"),
  field("rename-parent-seq", "目录内序号", "{parent_seq}", "动态值"),
  snippet("rename-parent-seq-pad3", "目录内三位序号", "{parent_seq.pad(3, '0')}", "动态值"),
  snippet("rename-now-full", "当前时间", "{now:yyyy-MM-dd HH-mm-ss}", "日期与时间"),
  snippet("rename-now-date", "当前日期", "{now:yyyy-MM-dd}", "日期与时间"),
  snippet("rename-now-year", "当前年份", "{now:yyyy}", "日期与时间"),
  snippet("rename-now-month", "当前月份", "{now:yyyy-MM}", "日期与时间"),
  snippet("rename-now-compact", "当前紧凑日期", "{now:yyyyMMdd}", "日期与时间"),
  snippet("rename-now-stamp", "当前紧凑时间戳", "{now:yyyyMMdd-HHmmss}", "日期与时间"),
  snippet("rename-created-full", "创建时间", "{date_created:yyyy-MM-dd HH-mm-ss}", "日期与时间"),
  snippet("rename-created-date", "创建日期", "{date_created:yyyy-MM-dd}", "日期与时间"),
  snippet("rename-created-year", "创建年份", "{date_created:yyyy}", "日期与时间"),
  snippet("rename-modified-full", "修改时间", "{date_modified:yyyy-MM-dd HH-mm-ss}", "日期与时间"),
  snippet("rename-modified-date", "修改日期", "{date_modified:yyyy-MM-dd}", "日期与时间"),
  snippet("rename-modified-year", "修改年份", "{date_modified:yyyy}", "日期与时间"),
  snippet("rename-dir-without-ext", "目录名不加扩展名", "{name}", "常用模板"),
  snippet("rename-folder-follow-video", "文件夹跟唯一视频同名", "{children.main_video.stem}", "常用模板"),
  snippet(
    "rename-clean-download",
    "清洗下载文件名",
    "{name.trim().remove_ads().remove_bracket_content().collapse_space()}{ext}",
    "常用模板",
  ),
  snippet("rename-use-parent-name", "用父目录名", "{parent}{ext}", "常用模板"),
  snippet("rename-numeric-use-parent", "数字名改用父目录", "{name.take_parent_if_numeric()}{ext}", "常用模板"),
  snippet("rename-cd-use-grandparent", "CD 目录改用祖父目录", "{parent.take_grandparent_if_cd()}", "常用模板"),
];

export const RENAME_CHAINS: AssistantItem[] = [
  chain("chain-trim", "去除首尾空格", ".trim()", "字符清理"),
  chain("chain-collapse-space", "合并连续空格", ".collapse_space()", "字符清理"),
  chain("chain-remove-space", "去掉全部空格", ".remove_space()", "字符清理"),
  chain("chain-sanitize", "清理非法文件名字符", ".sanitize()", "字符清理"),
  chain("chain-remove-ads", "移除广告文字和网址", ".remove_ads()", "字符清理"),
  chain("chain-dedupe", "字符去重", ".dedupe()", "字符清理"),
  chain("chain-normalize", "统一全角半角", ".normalize()", "字符清理"),
  chain("chain-to-simplified", "繁体转简体", ".to_simplified()", "字符清理"),
  chain("chain-to-traditional", "简体转繁体", ".to_traditional()", "字符清理"),
  chain("chain-to-halfwidth", "全角转半角", ".to_halfwidth()", "字符清理"),
  chain("chain-remove-punctuation", "移除标点符号", ".remove_punctuation()", "字符清理"),
  chain("chain-remove-brackets", "移除括号", ".remove_brackets()", "字符清理"),
  chain("chain-remove-bracket-content", "去掉括号及其内容", ".remove_bracket_content()", "字符清理"),
  chain("chain-remove-copy-suffix", "去掉副本后缀", ".remove_copy_suffix()", "字符清理"),
  chain("chain-collapse-dots", "点分隔改空格", ".collapse_dots()", "字符清理"),
  chain("chain-strip-ext-in-name", "去掉名字里误带的扩展名", ".strip_ext_in_name()", "字符清理"),
  chain("chain-remove-edition-tags", "去掉发行标签", ".remove_edition_tags()", "字符清理"),
  chain("chain-filename-safe-colon", "冒号改成全角", ".filename_safe_colon()", "字符清理"),
  chain("chain-zh-space-fix", "中英文之间补空格", ".zh_space_fix()", "字符清理"),
  chain("chain-remove-emoji", "去掉 emoji", ".remove_emoji()", "字符筛选"),
  chain(
    "chain-replace",
    "替换文字",
    ".replace('旧文字', '新文字')",
    "字符替换",
    [
      { name: "from", label: "原文字", defaultValue: "旧文字" },
      { name: "to", label: "新文字", defaultValue: "新文字" },
    ],
  ),
  chain(
    "chain-regex-replace",
    "正则替换",
    ".regex_replace('\\\\s+', '-')",
    "字符替换",
    [
      { name: "pattern", label: "正则", defaultValue: "\\\\s+" },
      { name: "replacement", label: "替换为", defaultValue: "-" },
    ],
  ),
  chain("chain-spaces-to-underscore", "空格改下划线", ".spaces_to_underscore()", "字符替换"),
  chain("chain-underscore-to-space", "下划线改空格", ".underscore_to_space()", "字符替换"),
  chain("chain-upper", "转为大写", ".upper()", "大小写格式"),
  chain("chain-lower", "转为小写", ".lower()", "大小写格式"),
  chain("chain-title", "单词首字母大写", ".title()", "大小写格式"),
  chain("chain-capitalize", "首字母大写", ".capitalize()", "大小写格式"),
  chain("chain-snake", "蛇形命名", ".snake_case()", "大小写格式"),
  chain("chain-kebab", "短横线命名", ".kebab_case()", "大小写格式"),
  chain("chain-camel", "小驼峰命名", ".camel_case()", "大小写格式"),
  chain("chain-pascal", "大驼峰命名", ".pascal_case()", "大小写格式"),
  chain("chain-constant", "常量命名", ".constant_case()", "大小写格式"),
  chain("chain-length", "统计字符长度", ".length()", "长度与截取"),
  chain(
    "chain-slice-10",
    "截取前 10 个字符",
    ".slice(0, 10)",
    "长度与截取",
    [
      { name: "start", label: "起始", defaultValue: "0" },
      { name: "end", label: "结束", defaultValue: "10" },
    ],
  ),
  chain("chain-slice-last-10", "截取后 10 个字符", ".slice(-10)", "长度与截取"),
  chain(
    "chain-truncate",
    "截取并追加省略号",
    ".truncate(10)",
    "长度与截取",
    [{ name: "limit", label: "长度", defaultValue: "10" }],
  ),
  chain(
    "chain-repeat",
    "重复字符 2 次",
    ".repeat(2)",
    "长度与截取",
    [{ name: "count", label: "次数（最多 20）", defaultValue: "2" }],
  ),
  chain("chain-reverse", "反转字符顺序", ".reverse()", "长度与截取"),
  chain("chain-first-word", "第一个词", ".first_word()", "长度与截取"),
  chain("chain-last-word", "最后一个词", ".last_word()", "长度与截取"),
  chain("chain-initials", "取首字母缩写", ".initials()", "长度与截取"),
  chain(
    "chain-nth-word",
    "第 n 个词",
    ".nth_word(1)",
    "长度与截取",
    [{ name: "index", label: "第几个（负数从后数）", defaultValue: "1" }],
  ),
  chain(
    "chain-split-at",
    "按分隔符取第 n 段",
    ".split_at('-', 1)",
    "长度与截取",
    [
      { name: "separator", label: "分隔符", defaultValue: "-" },
      { name: "index", label: "第几段", defaultValue: "1" },
    ],
  ),
  chain(
    "chain-insert",
    "指定位置插入文字",
    ".insert(0, '前缀')",
    "长度与截取",
    [
      { name: "index", label: "位置", defaultValue: "0" },
      { name: "text", label: "插入文字", defaultValue: "前缀" },
    ],
  ),
  chain("chain-keep-digits", "只保留数字", ".keep_digits()", "字符筛选"),
  chain("chain-remove-digits", "移除数字", ".remove_digits()", "字符筛选"),
  chain("chain-keep-letters", "只保留字母", ".keep_letters()", "字符筛选"),
  chain("chain-remove-letters", "移除字母", ".remove_letters()", "字符筛选"),
  chain("chain-keep-alnum", "只保留字母和数字", ".keep_alnum()", "字符筛选"),
  chain("chain-keep-ascii", "只保留 ASCII", ".keep_ascii()", "字符筛选"),
  chain("chain-extract-year", "提取年份", ".extract_year()", "抽取"),
  chain("chain-extract-number", "提取第一个数字", ".extract_number()", "抽取"),
  chain("chain-extract-last-number", "提取最后一个数字", ".extract_last_number()", "抽取"),
  chain("chain-extract-resolution", "提取分辨率", ".extract_resolution()", "抽取"),
  chain("chain-normalize-resolution", "分辨率归一", ".normalize_resolution()", "抽取"),
  chain("chain-extract-season-episode", "提取季集", ".extract_season_episode()", "抽取"),
  chain("chain-extract-episode", "提取集数", ".extract_episode()", "抽取"),
  chain("chain-extract-source", "提取片源", ".extract_source()", "抽取"),
  chain("chain-remove-year", "去掉年份", ".remove_year()", "字符筛选"),
  chain(
    "chain-extract-date",
    "提取日期",
    ".extract_date('yyyy-MM-dd')",
    "抽取",
    [{ name: "format", label: "格式", defaultValue: "yyyy-MM-dd" }],
  ),
  chain(
    "chain-match",
    "正则捕获",
    ".match('(.+)')",
    "抽取",
    [{ name: "pattern", label: "正则", defaultValue: "(.+)" }],
  ),
  chain(
    "chain-before",
    "截取某段之前",
    ".before('-')",
    "抽取",
    [{ name: "needle", label: "分隔文字", defaultValue: "-" }],
  ),
  chain(
    "chain-after",
    "截取某段之后",
    ".after('-')",
    "抽取",
    [{ name: "needle", label: "分隔文字", defaultValue: "-" }],
  ),
  chain(
    "chain-between",
    "截取两段之间",
    ".between('[', ']')",
    "抽取",
    [
      { name: "start", label: "开始", defaultValue: "[" },
      { name: "end", label: "结束", defaultValue: "]" },
    ],
  ),
  chain(
    "chain-pad",
    "补齐到 2 位",
    ".pad(2, '0')",
    "格式补齐",
    [
      { name: "width", label: "宽度", defaultValue: "2" },
      { name: "fill", label: "填充", defaultValue: "0" },
    ],
  ),
  chain("chain-pad-start", "开头补齐到 3 位", ".pad_start(3, '0')", "格式补齐"),
  chain("chain-pad-end", "末尾补齐到 10 位", ".pad_end(10, '0')", "格式补齐"),
  chain(
    "chain-pad-number",
    "抽出数字并补齐",
    ".pad_number(3, '0')",
    "格式补齐",
    [
      { name: "width", label: "宽度", defaultValue: "3" },
      { name: "fill", label: "填充", defaultValue: "0" },
    ],
  ),
  chain(
    "chain-prefix",
    "添加前缀",
    ".prefix('前缀_')",
    "格式补齐",
    [{ name: "text", label: "前缀", defaultValue: "前缀_" }],
  ),
  chain(
    "chain-suffix",
    "添加后缀",
    ".suffix('_副本')",
    "格式补齐",
    [{ name: "text", label: "后缀", defaultValue: "_副本" }],
  ),
  chain("chain-ensure-prefix", "确保有前缀", ".ensure_prefix('IMG_')", "格式补齐"),
  chain("chain-ensure-suffix", "确保有后缀", ".ensure_suffix('_final')", "格式补齐"),
  chain("chain-remove-prefix", "去掉指定前缀", ".remove_prefix('IMG_')", "格式补齐"),
  chain("chain-remove-suffix", "去掉指定后缀", ".remove_suffix('_副本')", "格式补齐"),
  chain(
    "chain-wrap",
    "左右包裹",
    ".wrap('[', ']')",
    "格式补齐",
    [
      { name: "left", label: "左侧", defaultValue: "[" },
      { name: "right", label: "右侧", defaultValue: "]" },
    ],
  ),
  chain(
    "chain-if-empty",
    "为空时使用默认值",
    ".if_empty('未命名')",
    "格式补齐",
    [{ name: "fallback", label: "默认值", defaultValue: "未命名" }],
  ),
  chain(
    "chain-if-contains",
    "包含某词则替换",
    ".if_contains('4K', '[4K]')",
    "格式补齐",
    [
      { name: "needle", label: "包含文字", defaultValue: "4K" },
      { name: "replacement", label: "替换为", defaultValue: "[4K]" },
    ],
  ),
  chain(
    "chain-max-len",
    "按剩余路径长度截断",
    ".max_len()",
    "长度与截取",
    [{ name: "limit", label: "最长字符数（可空，按路径剩余长度）", defaultValue: "" }],
  ),
  chain("chain-take-parent-if-numeric", "数字名改用父目录", ".take_parent_if_numeric()", "格式补齐"),
  chain("chain-take-grandparent-if-cd", "CD 层改用祖父目录", ".take_grandparent_if_cd()", "格式补齐"),
  chain("chain-ensure-ext", "补回扩展名", ".ensure_ext()", "格式补齐"),
  chain("chain-format-size", "格式化为友好大小", ".format_size()", "格式补齐"),
  chain("chain-slice-from-2", "截取从第 3 个字符起", ".slice(2)", "长度与截取"),
];

/** The same string operations are available to every rule filter, regardless
 * of whether the source is a file name, directory name, or path field. */
const RULE_FIELD_DEFINITIONS: Array<[string, string]> = [
  ["name", "当前名称（不含扩展名）"],
  ["stem", "文件主干名"],
  ["filename", "完整文件名"],
  ["folder_name", "文件夹名称"],
  ["file_name", "文件完整名称"],
  ["parent", "所在目录名"],
  ["grandparent", "上级目录名"],
  ["path", "完整路径"],
  ["relPath", "相对路径"],
  ["ext", "扩展名"],
];

export const RULE_FIELDS: AssistantItem[] = RULE_FIELD_DEFINITIONS.map(([fieldName, label]) => ({
  id: `rule-field-${fieldName}`,
  label,
  value: `${fieldName}:`,
  group: "字符串来源",
  kind: "field",
  engine: "rule-field",
  contexts: RULE,
}));

export const RULE_CHAINS: AssistantItem[] = RENAME_CHAINS.map((item) => ({
  ...item,
  id: `rule-${item.id}`,
  engine: "rule-chain" as const,
  contexts: RULE,
}));

export const RENAME_CHAIN_FUNCS = CHAIN_FUNCS;
